import * as fs from "fs";
import * as path from "path";
import { calendars } from "../data/calendars";
import type { CalendarEvent } from "../types/CalendarEvent";

function unfoldLines(raw: string): string[] {
  const lines = raw.replace(/\r\n/g, "\n").split("\n");
  const out: string[] = [];
  for (const line of lines) {
    if (line.startsWith(" ") || line.startsWith("\t")) {
      // continuation: append to previous
      if (out.length === 0) out.push(line.trim());
      else out[out.length - 1] += line.slice(1);
    } else {
      out.push(line);
    }
  }
  return out;
}

function parseIcs(content: string): CalendarEvent[] {
  const lines = unfoldLines(content);
  const events: string[][] = [];
  let inEvent = false;
  let current: string[] = [];
  for (const line of lines) {
    if (line === "BEGIN:VEVENT") {
      inEvent = true;
      current = [];
      continue;
    }
    if (line === "END:VEVENT") {
      inEvent = false;
      events.push(current.slice());
      current = [];
      continue;
    }
    if (inEvent) current.push(line);
  }

  const out: CalendarEvent[] = [];

  for (const ev of events) {
    const props: Record<string, string> = {};
    for (const line of ev) {
      const idx = line.indexOf(":");
      if (idx === -1) continue;
      const keyWithParams = line.slice(0, idx);
      const value = line.slice(idx + 1);
      const key = keyWithParams.split(";")[0];
      props[key] = value;
    }

    out.push(props);
  }

  return out;
}

function eventsToTsContent(varName: string, events: CalendarEvent[]): string {
  const header = `// Auto-generated by process-calendars.ts\n// Do not edit by hand.\n\n`;
  const importType = `import type { CalendarEvent } from "../types/CalendarEvent";\n\n`;

  const body = `export const ${varName}: CalendarEvent[] = ${JSON.stringify(events, null, 2)};\n`;

  return header + importType + body;
}

async function run(): Promise<void> {
  try {
    for (const cal of calendars) {
      if (!fs.existsSync(cal.file)) {
        console.warn(`Skipping ${cal.name}: calendar file not found at ${cal.file}`);
        continue;
      }

      const raw = fs.readFileSync(cal.file, "utf8");
      const events = parseIcs(raw);
      const varName = `${cal.name.toLowerCase()}CalendarEvents`;
      const content = eventsToTsContent(varName, events);

      const outPath = cal.calendarEventsFile;
      const outDir = path.dirname(outPath);
      if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

      fs.writeFileSync(outPath, content, "utf8");
      console.log(`Wrote ${outPath} (${events.length} calendar events)`);
      console.log("");
    }
  } catch (err) {
    console.error("process-calendars failed:", err);
    process.exit(1);
  }
}

run();
