// Auto-generated by process-calendars.ts
// Do not edit by hand.

import type { RaceSession } from "../types/RaceSession";

export const f1Sessions: RaceSession[] = [
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-03-06T01:30:00.000Z",
    endDatetime: "2026-03-06T02:30:00.000Z",
    coords: {
      lat: -37.8373,
      lon: 144.9666,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-03-06T05:00:00.000Z",
    endDatetime: "2026-03-06T06:00:00.000Z",
    coords: {
      lat: -37.8373,
      lon: 144.9666,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-03-07T01:30:00.000Z",
    endDatetime: "2026-03-07T02:30:00.000Z",
    coords: {
      lat: -37.8373,
      lon: 144.9666,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-03-07T05:00:00.000Z",
    endDatetime: "2026-03-07T06:00:00.000Z",
    coords: {
      lat: -37.8373,
      lon: 144.9666,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-03-08T04:00:00.000Z",
    endDatetime: "2026-03-08T06:00:00.000Z",
    coords: {
      lat: -37.8373,
      lon: 144.9666,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-03-13T03:30:00.000Z",
    endDatetime: "2026-03-13T04:30:00.000Z",
    coords: {
      lat: 31.3807,
      lon: 121.2498,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint-qualifying",
    startDateTime: "2026-03-13T07:30:00.000Z",
    endDatetime: "2026-03-13T08:15:00.000Z",
    coords: {
      lat: 31.3807,
      lon: 121.2498,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint",
    startDateTime: "2026-03-14T03:00:00.000Z",
    endDatetime: "2026-03-14T03:30:00.000Z",
    coords: {
      lat: 31.3807,
      lon: 121.2498,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-03-14T07:00:00.000Z",
    endDatetime: "2026-03-14T08:00:00.000Z",
    coords: {
      lat: 31.3807,
      lon: 121.2498,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-03-15T07:00:00.000Z",
    endDatetime: "2026-03-15T09:00:00.000Z",
    coords: {
      lat: 31.3807,
      lon: 121.2498,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-03-27T02:30:00.000Z",
    endDatetime: "2026-03-27T03:30:00.000Z",
    coords: {
      lat: 35.3689,
      lon: 138.9256,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-03-27T06:00:00.000Z",
    endDatetime: "2026-03-27T07:00:00.000Z",
    coords: {
      lat: 35.3689,
      lon: 138.9256,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-03-28T02:30:00.000Z",
    endDatetime: "2026-03-28T03:30:00.000Z",
    coords: {
      lat: 35.3689,
      lon: 138.9256,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-03-28T06:00:00.000Z",
    endDatetime: "2026-03-28T07:00:00.000Z",
    coords: {
      lat: 35.3689,
      lon: 138.9256,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-03-29T05:00:00.000Z",
    endDatetime: "2026-03-29T07:00:00.000Z",
    coords: {
      lat: 35.3689,
      lon: 138.9256,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-04-10T11:30:00.000Z",
    endDatetime: "2026-04-10T12:30:00.000Z",
    coords: {
      lat: 26.037,
      lon: 50.5112,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-04-10T15:00:00.000Z",
    endDatetime: "2026-04-10T16:00:00.000Z",
    coords: {
      lat: 26.037,
      lon: 50.5112,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-04-11T12:30:00.000Z",
    endDatetime: "2026-04-11T13:30:00.000Z",
    coords: {
      lat: 26.037,
      lon: 50.5112,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-04-11T16:00:00.000Z",
    endDatetime: "2026-04-11T17:00:00.000Z",
    coords: {
      lat: 26.037,
      lon: 50.5112,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-04-12T15:00:00.000Z",
    endDatetime: "2026-04-12T17:00:00.000Z",
    coords: {
      lat: 26.037,
      lon: 50.5112,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-04-17T13:30:00.000Z",
    endDatetime: "2026-04-17T14:30:00.000Z",
    coords: {
      lat: 21.485811,
      lon: 39.192505,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-04-17T17:00:00.000Z",
    endDatetime: "2026-04-17T18:00:00.000Z",
    coords: {
      lat: 21.485811,
      lon: 39.192505,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-04-18T13:30:00.000Z",
    endDatetime: "2026-04-18T14:30:00.000Z",
    coords: {
      lat: 21.485811,
      lon: 39.192505,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-04-18T17:00:00.000Z",
    endDatetime: "2026-04-18T18:00:00.000Z",
    coords: {
      lat: 21.485811,
      lon: 39.192505,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-04-19T17:00:00.000Z",
    endDatetime: "2026-04-19T19:00:00.000Z",
    coords: {
      lat: 21.485811,
      lon: 39.192505,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-05-01T16:30:00.000Z",
    endDatetime: "2026-05-01T17:30:00.000Z",
    coords: {
      lat: 25.957764,
      lon: -80.238835,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint-qualifying",
    startDateTime: "2026-05-01T20:30:00.000Z",
    endDatetime: "2026-05-01T21:15:00.000Z",
    coords: {
      lat: 25.957764,
      lon: -80.238835,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint",
    startDateTime: "2026-05-02T16:00:00.000Z",
    endDatetime: "2026-05-02T16:30:00.000Z",
    coords: {
      lat: 25.957764,
      lon: -80.238835,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-05-02T20:00:00.000Z",
    endDatetime: "2026-05-02T21:00:00.000Z",
    coords: {
      lat: 25.957764,
      lon: -80.238835,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-05-03T20:00:00.000Z",
    endDatetime: "2026-05-03T22:00:00.000Z",
    coords: {
      lat: 25.957764,
      lon: -80.238835,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-05-22T16:30:00.000Z",
    endDatetime: "2026-05-22T17:30:00.000Z",
    coords: {
      lat: 45.5034,
      lon: -73.5267,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint-qualifying",
    startDateTime: "2026-05-22T20:30:00.000Z",
    endDatetime: "2026-05-22T21:15:00.000Z",
    coords: {
      lat: 45.5034,
      lon: -73.5267,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint",
    startDateTime: "2026-05-23T16:00:00.000Z",
    endDatetime: "2026-05-23T16:30:00.000Z",
    coords: {
      lat: 45.5034,
      lon: -73.5267,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-05-23T20:00:00.000Z",
    endDatetime: "2026-05-23T21:00:00.000Z",
    coords: {
      lat: 45.5034,
      lon: -73.5267,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-05-24T20:00:00.000Z",
    endDatetime: "2026-05-24T22:00:00.000Z",
    coords: {
      lat: 45.5034,
      lon: -73.5267,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-06-05T11:30:00.000Z",
    endDatetime: "2026-06-05T12:30:00.000Z",
    coords: {
      lat: 43.7338,
      lon: 7.4215,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-06-05T15:00:00.000Z",
    endDatetime: "2026-06-05T16:00:00.000Z",
    coords: {
      lat: 43.7338,
      lon: 7.4215,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-06-06T10:30:00.000Z",
    endDatetime: "2026-06-06T11:30:00.000Z",
    coords: {
      lat: 43.7338,
      lon: 7.4215,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-06-06T14:00:00.000Z",
    endDatetime: "2026-06-06T15:00:00.000Z",
    coords: {
      lat: 43.7338,
      lon: 7.4215,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-06-07T13:00:00.000Z",
    endDatetime: "2026-06-07T15:00:00.000Z",
    coords: {
      lat: 43.7338,
      lon: 7.4215,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-06-12T11:30:00.000Z",
    endDatetime: "2026-06-12T12:30:00.000Z",
    coords: {
      lat: 41.5638,
      lon: 2.2585,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-06-12T15:00:00.000Z",
    endDatetime: "2026-06-12T16:00:00.000Z",
    coords: {
      lat: 41.5638,
      lon: 2.2585,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-06-13T10:30:00.000Z",
    endDatetime: "2026-06-13T11:30:00.000Z",
    coords: {
      lat: 41.5638,
      lon: 2.2585,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-06-13T14:00:00.000Z",
    endDatetime: "2026-06-13T15:00:00.000Z",
    coords: {
      lat: 41.5638,
      lon: 2.2585,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-06-14T13:00:00.000Z",
    endDatetime: "2026-06-14T15:00:00.000Z",
    coords: {
      lat: 41.5638,
      lon: 2.2585,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-06-26T11:30:00.000Z",
    endDatetime: "2026-06-26T12:30:00.000Z",
    coords: {
      lat: 47.2225,
      lon: 14.7607,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-06-26T15:00:00.000Z",
    endDatetime: "2026-06-26T16:00:00.000Z",
    coords: {
      lat: 47.2225,
      lon: 14.7607,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-06-27T10:30:00.000Z",
    endDatetime: "2026-06-27T11:30:00.000Z",
    coords: {
      lat: 47.2225,
      lon: 14.7607,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-06-27T14:00:00.000Z",
    endDatetime: "2026-06-27T15:00:00.000Z",
    coords: {
      lat: 47.2225,
      lon: 14.7607,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-06-28T13:00:00.000Z",
    endDatetime: "2026-06-28T15:00:00.000Z",
    coords: {
      lat: 47.2225,
      lon: 14.7607,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-07-03T11:30:00.000Z",
    endDatetime: "2026-07-03T12:30:00.000Z",
    coords: {
      lat: 52.0706,
      lon: -1.0174,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint-qualifying",
    startDateTime: "2026-07-03T15:30:00.000Z",
    endDatetime: "2026-07-03T16:15:00.000Z",
    coords: {
      lat: 52.0706,
      lon: -1.0174,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint",
    startDateTime: "2026-07-04T11:00:00.000Z",
    endDatetime: "2026-07-04T11:30:00.000Z",
    coords: {
      lat: 52.0706,
      lon: -1.0174,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-07-04T15:00:00.000Z",
    endDatetime: "2026-07-04T16:00:00.000Z",
    coords: {
      lat: 52.0706,
      lon: -1.0174,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-07-05T14:00:00.000Z",
    endDatetime: "2026-07-05T16:00:00.000Z",
    coords: {
      lat: 52.0706,
      lon: -1.0174,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-07-17T11:30:00.000Z",
    endDatetime: "2026-07-17T12:30:00.000Z",
    coords: {
      lat: 50.444,
      lon: 5.9687,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-07-17T15:00:00.000Z",
    endDatetime: "2026-07-17T16:00:00.000Z",
    coords: {
      lat: 50.444,
      lon: 5.9687,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-07-18T10:30:00.000Z",
    endDatetime: "2026-07-18T11:30:00.000Z",
    coords: {
      lat: 50.444,
      lon: 5.9687,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-07-18T14:00:00.000Z",
    endDatetime: "2026-07-18T15:00:00.000Z",
    coords: {
      lat: 50.444,
      lon: 5.9687,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-07-19T13:00:00.000Z",
    endDatetime: "2026-07-19T15:00:00.000Z",
    coords: {
      lat: 50.444,
      lon: 5.9687,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-07-24T11:30:00.000Z",
    endDatetime: "2026-07-24T12:30:00.000Z",
    coords: {
      lat: 47.583,
      lon: 19.2526,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-07-24T15:00:00.000Z",
    endDatetime: "2026-07-24T16:00:00.000Z",
    coords: {
      lat: 47.583,
      lon: 19.2526,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-07-25T10:30:00.000Z",
    endDatetime: "2026-07-25T11:30:00.000Z",
    coords: {
      lat: 47.583,
      lon: 19.2526,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-07-25T14:00:00.000Z",
    endDatetime: "2026-07-25T15:00:00.000Z",
    coords: {
      lat: 47.583,
      lon: 19.2526,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-07-26T13:00:00.000Z",
    endDatetime: "2026-07-26T15:00:00.000Z",
    coords: {
      lat: 47.583,
      lon: 19.2526,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-08-21T10:30:00.000Z",
    endDatetime: "2026-08-21T11:30:00.000Z",
    coords: {
      lat: 52.388408,
      lon: 4.547122,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint-qualifying",
    startDateTime: "2026-08-21T14:30:00.000Z",
    endDatetime: "2026-08-21T15:15:00.000Z",
    coords: {
      lat: 52.388408,
      lon: 4.547122,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint",
    startDateTime: "2026-08-22T10:00:00.000Z",
    endDatetime: "2026-08-22T10:30:00.000Z",
    coords: {
      lat: 52.388408,
      lon: 4.547122,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-08-22T14:00:00.000Z",
    endDatetime: "2026-08-22T15:00:00.000Z",
    coords: {
      lat: 52.388408,
      lon: 4.547122,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-08-23T13:00:00.000Z",
    endDatetime: "2026-08-23T15:00:00.000Z",
    coords: {
      lat: 52.388408,
      lon: 4.547122,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-09-04T10:30:00.000Z",
    endDatetime: "2026-09-04T11:30:00.000Z",
    coords: {
      lat: 45.6169,
      lon: 9.2825,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-09-04T14:00:00.000Z",
    endDatetime: "2026-09-04T15:00:00.000Z",
    coords: {
      lat: 45.6169,
      lon: 9.2825,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-09-05T10:30:00.000Z",
    endDatetime: "2026-09-05T11:30:00.000Z",
    coords: {
      lat: 45.6169,
      lon: 9.2825,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-09-05T14:00:00.000Z",
    endDatetime: "2026-09-05T15:00:00.000Z",
    coords: {
      lat: 45.6169,
      lon: 9.2825,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-09-06T13:00:00.000Z",
    endDatetime: "2026-09-06T15:00:00.000Z",
    coords: {
      lat: 45.6169,
      lon: 9.2825,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-09-11T11:30:00.000Z",
    endDatetime: "2026-09-11T12:30:00.000Z",
    coords: {
      lat: 40.4168,
      lon: -3.7038,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-09-11T15:00:00.000Z",
    endDatetime: "2026-09-11T16:00:00.000Z",
    coords: {
      lat: 40.4168,
      lon: -3.7038,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-09-12T10:30:00.000Z",
    endDatetime: "2026-09-12T11:30:00.000Z",
    coords: {
      lat: 40.4168,
      lon: -3.7038,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-09-12T14:00:00.000Z",
    endDatetime: "2026-09-12T15:00:00.000Z",
    coords: {
      lat: 40.4168,
      lon: -3.7038,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-09-13T13:00:00.000Z",
    endDatetime: "2026-09-13T15:00:00.000Z",
    coords: {
      lat: 40.4168,
      lon: -3.7038,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-09-24T08:30:00.000Z",
    endDatetime: "2026-09-24T09:30:00.000Z",
    coords: {
      lat: 40.3699,
      lon: 49.8433,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-09-24T12:00:00.000Z",
    endDatetime: "2026-09-24T13:00:00.000Z",
    coords: {
      lat: 40.3699,
      lon: 49.8433,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-09-25T08:30:00.000Z",
    endDatetime: "2026-09-25T09:30:00.000Z",
    coords: {
      lat: 40.3699,
      lon: 49.8433,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-09-25T12:00:00.000Z",
    endDatetime: "2026-09-25T13:00:00.000Z",
    coords: {
      lat: 40.3699,
      lon: 49.8433,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-09-26T11:00:00.000Z",
    endDatetime: "2026-09-26T13:00:00.000Z",
    coords: {
      lat: 40.3699,
      lon: 49.8433,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-10-09T09:30:00.000Z",
    endDatetime: "2026-10-09T10:30:00.000Z",
    coords: {
      lat: 1.2857,
      lon: 103.8575,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint-qualifying",
    startDateTime: "2026-10-09T12:30:00.000Z",
    endDatetime: "2026-10-09T13:15:00.000Z",
    coords: {
      lat: 1.2857,
      lon: 103.8575,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "sprint",
    startDateTime: "2026-10-10T09:00:00.000Z",
    endDatetime: "2026-10-10T09:30:00.000Z",
    coords: {
      lat: 1.2857,
      lon: 103.8575,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-10-10T13:00:00.000Z",
    endDatetime: "2026-10-10T14:00:00.000Z",
    coords: {
      lat: 1.2857,
      lon: 103.8575,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-10-11T12:00:00.000Z",
    endDatetime: "2026-10-11T14:00:00.000Z",
    coords: {
      lat: 1.2857,
      lon: 103.8575,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-10-23T17:30:00.000Z",
    endDatetime: "2026-10-23T18:30:00.000Z",
    coords: {
      lat: 30.1328,
      lon: -97.6411,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-10-23T21:00:00.000Z",
    endDatetime: "2026-10-23T22:00:00.000Z",
    coords: {
      lat: 30.1328,
      lon: -97.6411,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-10-24T17:30:00.000Z",
    endDatetime: "2026-10-24T18:30:00.000Z",
    coords: {
      lat: 30.1328,
      lon: -97.6411,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-10-24T21:00:00.000Z",
    endDatetime: "2026-10-24T22:00:00.000Z",
    coords: {
      lat: 30.1328,
      lon: -97.6411,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-10-25T20:00:00.000Z",
    endDatetime: "2026-10-25T22:00:00.000Z",
    coords: {
      lat: 30.1328,
      lon: -97.6411,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-10-30T18:30:00.000Z",
    endDatetime: "2026-10-30T19:30:00.000Z",
    coords: {
      lat: 19.4028,
      lon: -99.0986,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-10-30T22:00:00.000Z",
    endDatetime: "2026-10-30T23:00:00.000Z",
    coords: {
      lat: 19.4028,
      lon: -99.0986,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-10-31T17:30:00.000Z",
    endDatetime: "2026-10-31T18:30:00.000Z",
    coords: {
      lat: 19.4028,
      lon: -99.0986,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-10-31T21:00:00.000Z",
    endDatetime: "2026-10-31T22:00:00.000Z",
    coords: {
      lat: 19.4028,
      lon: -99.0986,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-11-01T20:00:00.000Z",
    endDatetime: "2026-11-01T22:00:00.000Z",
    coords: {
      lat: 19.4028,
      lon: -99.0986,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-11-06T15:30:00.000Z",
    endDatetime: "2026-11-06T16:30:00.000Z",
    coords: {
      lat: -23.7014,
      lon: -46.6969,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-11-06T19:00:00.000Z",
    endDatetime: "2026-11-06T20:00:00.000Z",
    coords: {
      lat: -23.7014,
      lon: -46.6969,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-11-07T14:30:00.000Z",
    endDatetime: "2026-11-07T15:30:00.000Z",
    coords: {
      lat: -23.7014,
      lon: -46.6969,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-11-07T18:00:00.000Z",
    endDatetime: "2026-11-07T19:00:00.000Z",
    coords: {
      lat: -23.7014,
      lon: -46.6969,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-11-08T17:00:00.000Z",
    endDatetime: "2026-11-08T19:00:00.000Z",
    coords: {
      lat: -23.7014,
      lon: -46.6969,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-11-20T00:30:00.000Z",
    endDatetime: "2026-11-20T01:30:00.000Z",
    coords: {
      lat: 36.166747,
      lon: -115.148708,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-11-20T04:00:00.000Z",
    endDatetime: "2026-11-20T05:00:00.000Z",
    coords: {
      lat: 36.166747,
      lon: -115.148708,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-11-21T00:30:00.000Z",
    endDatetime: "2026-11-21T01:30:00.000Z",
    coords: {
      lat: 36.166747,
      lon: -115.148708,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-11-21T04:00:00.000Z",
    endDatetime: "2026-11-21T05:00:00.000Z",
    coords: {
      lat: 36.166747,
      lon: -115.148708,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-11-22T04:00:00.000Z",
    endDatetime: "2026-11-22T06:00:00.000Z",
    coords: {
      lat: 36.166747,
      lon: -115.148708,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-11-27T13:30:00.000Z",
    endDatetime: "2026-11-27T14:30:00.000Z",
    coords: {
      lat: 25.490292,
      lon: 51.45303,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-11-27T17:00:00.000Z",
    endDatetime: "2026-11-27T18:00:00.000Z",
    coords: {
      lat: 25.490292,
      lon: 51.45303,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-11-28T14:30:00.000Z",
    endDatetime: "2026-11-28T15:30:00.000Z",
    coords: {
      lat: 25.490292,
      lon: 51.45303,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-11-28T18:00:00.000Z",
    endDatetime: "2026-11-28T19:00:00.000Z",
    coords: {
      lat: 25.490292,
      lon: 51.45303,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-11-29T16:00:00.000Z",
    endDatetime: "2026-11-29T18:00:00.000Z",
    coords: {
      lat: 25.490292,
      lon: 51.45303,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-1",
    startDateTime: "2026-12-04T09:30:00.000Z",
    endDatetime: "2026-12-04T10:30:00.000Z",
    coords: {
      lat: 24.4821,
      lon: 54.3482,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-2",
    startDateTime: "2026-12-04T13:00:00.000Z",
    endDatetime: "2026-12-04T14:00:00.000Z",
    coords: {
      lat: 24.4821,
      lon: 54.3482,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "free-practice-3",
    startDateTime: "2026-12-05T10:30:00.000Z",
    endDatetime: "2026-12-05T11:30:00.000Z",
    coords: {
      lat: 24.4821,
      lon: 54.3482,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "qualifying",
    startDateTime: "2026-12-05T14:00:00.000Z",
    endDatetime: "2026-12-05T15:00:00.000Z",
    coords: {
      lat: 24.4821,
      lon: 54.3482,
    },
  },
  {
    formulaSlug: "f1",
    sessionTypeSlug: "grand-prix",
    startDateTime: "2026-12-06T13:00:00.000Z",
    endDatetime: "2026-12-06T15:00:00.000Z",
    coords: {
      lat: 24.4821,
      lon: 54.3482,
    },
  },
];
