// Auto-generated by process-calendars.ts
// Do not edit by hand.

import type { RaceSession } from "../types/RaceSession";

export const f2Sessions: RaceSession[] = [
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-03-13T23:00:00.000Z",
    endDatetime: "2025-03-13T23:45:00.000Z",
    coords: {
      lat: -37.8373,
      lon: 144.9666,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-03-14T06:30:00.000Z",
    endDatetime: "2025-03-14T07:00:00.000Z",
    coords: {
      lat: -37.8373,
      lon: 144.9666,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-03-15T03:15:00.000Z",
    endDatetime: "2025-03-15T04:00:00.000Z",
    coords: {
      lat: -37.8373,
      lon: 144.9666,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-03-16T00:30:00.000Z",
    endDatetime: "2025-03-16T01:30:00.000Z",
    coords: {
      lat: -37.8373,
      lon: 144.9666,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-04-11T09:05:00.000Z",
    endDatetime: "2025-04-11T09:50:00.000Z",
    coords: {
      lat: 26.037,
      lon: 50.5112,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-04-11T13:55:00.000Z",
    endDatetime: "2025-04-11T14:25:00.000Z",
    coords: {
      lat: 26.037,
      lon: 50.5112,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-04-12T14:15:00.000Z",
    endDatetime: "2025-04-12T15:00:00.000Z",
    coords: {
      lat: 26.037,
      lon: 50.5112,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-04-13T11:25:00.000Z",
    endDatetime: "2025-04-13T12:25:00.000Z",
    coords: {
      lat: 26.037,
      lon: 50.5112,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-04-18T09:45:00.000Z",
    endDatetime: "2025-04-18T10:30:00.000Z",
    coords: {
      lat: 21.485811,
      lon: 39.192505,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-04-18T15:00:00.000Z",
    endDatetime: "2025-04-18T15:30:00.000Z",
    coords: {
      lat: 21.485811,
      lon: 39.192505,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-04-19T15:15:00.000Z",
    endDatetime: "2025-04-19T16:00:00.000Z",
    coords: {
      lat: 21.485811,
      lon: 39.192505,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-04-20T13:25:00.000Z",
    endDatetime: "2025-04-20T14:25:00.000Z",
    coords: {
      lat: 21.485811,
      lon: 39.192505,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-05-16T09:05:00.000Z",
    endDatetime: "2025-05-16T09:50:00.000Z",
    coords: {
      lat: 44.344576,
      lon: 11.713808,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-05-16T14:00:00.000Z",
    endDatetime: "2025-05-16T14:30:00.000Z",
    coords: {
      lat: 44.344576,
      lon: 11.713808,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-05-17T12:15:00.000Z",
    endDatetime: "2025-05-17T13:00:00.000Z",
    coords: {
      lat: 44.344576,
      lon: 11.713808,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-05-18T08:00:00.000Z",
    endDatetime: "2025-05-18T09:00:00.000Z",
    coords: {
      lat: 44.344576,
      lon: 11.713808,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-05-22T13:00:00.000Z",
    endDatetime: "2025-05-22T13:45:00.000Z",
    coords: {
      lat: 43.7338,
      lon: 7.4215,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-05-23T13:10:00.000Z",
    endDatetime: "2025-05-23T13:40:00.000Z",
    coords: {
      lat: 43.7338,
      lon: 7.4215,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-05-24T12:15:00.000Z",
    endDatetime: "2025-05-24T13:00:00.000Z",
    coords: {
      lat: 43.7338,
      lon: 7.4215,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-05-25T07:40:00.000Z",
    endDatetime: "2025-05-25T08:40:00.000Z",
    coords: {
      lat: 43.7338,
      lon: 7.4215,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-05-30T09:05:00.000Z",
    endDatetime: "2025-05-30T09:50:00.000Z",
    coords: {
      lat: 41.5638,
      lon: 2.2585,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-05-30T13:55:00.000Z",
    endDatetime: "2025-05-30T14:25:00.000Z",
    coords: {
      lat: 41.5638,
      lon: 2.2585,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-05-31T12:15:00.000Z",
    endDatetime: "2025-05-31T13:00:00.000Z",
    coords: {
      lat: 41.5638,
      lon: 2.2585,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-06-01T08:00:00.000Z",
    endDatetime: "2025-06-01T09:00:00.000Z",
    coords: {
      lat: 41.5638,
      lon: 2.2585,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-06-27T09:05:00.000Z",
    endDatetime: "2025-06-27T09:50:00.000Z",
    coords: {
      lat: 47.2225,
      lon: 14.7607,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-06-27T13:55:00.000Z",
    endDatetime: "2025-06-27T14:25:00.000Z",
    coords: {
      lat: 47.2225,
      lon: 14.7607,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-06-28T12:15:00.000Z",
    endDatetime: "2025-06-28T13:00:00.000Z",
    coords: {
      lat: 47.2225,
      lon: 14.7607,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-06-29T08:00:00.000Z",
    endDatetime: "2025-06-29T09:00:00.000Z",
    coords: {
      lat: 47.2225,
      lon: 14.7607,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-07-04T09:00:00.000Z",
    endDatetime: "2025-07-04T09:45:00.000Z",
    coords: {
      lat: 52.0706,
      lon: -1.0174,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-07-04T13:55:00.000Z",
    endDatetime: "2025-07-04T14:25:00.000Z",
    coords: {
      lat: 52.0706,
      lon: -1.0174,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-07-05T12:15:00.000Z",
    endDatetime: "2025-07-05T13:00:00.000Z",
    coords: {
      lat: 52.0706,
      lon: -1.0174,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-07-06T10:05:00.000Z",
    endDatetime: "2025-07-06T11:05:00.000Z",
    coords: {
      lat: 52.0706,
      lon: -1.0174,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-07-25T08:10:00.000Z",
    endDatetime: "2025-07-25T08:55:00.000Z",
    coords: {
      lat: 50.444,
      lon: 5.9687,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-07-25T13:00:00.000Z",
    endDatetime: "2025-07-25T13:30:00.000Z",
    coords: {
      lat: 50.444,
      lon: 5.9687,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-07-26T11:45:00.000Z",
    endDatetime: "2025-07-26T12:30:00.000Z",
    coords: {
      lat: 50.444,
      lon: 5.9687,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-07-27T08:00:00.000Z",
    endDatetime: "2025-07-27T09:00:00.000Z",
    coords: {
      lat: 50.444,
      lon: 5.9687,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-08-01T09:05:00.000Z",
    endDatetime: "2025-08-01T09:50:00.000Z",
    coords: {
      lat: 47.583,
      lon: 19.2526,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-08-01T13:55:00.000Z",
    endDatetime: "2025-08-01T14:25:00.000Z",
    coords: {
      lat: 47.583,
      lon: 19.2526,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-08-02T12:15:00.000Z",
    endDatetime: "2025-08-02T13:00:00.000Z",
    coords: {
      lat: 47.583,
      lon: 19.2526,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-08-03T08:00:00.000Z",
    endDatetime: "2025-08-03T09:00:00.000Z",
    coords: {
      lat: 47.583,
      lon: 19.2526,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-09-05T09:00:00.000Z",
    endDatetime: "2025-09-05T09:45:00.000Z",
    coords: {
      lat: 45.6169,
      lon: 9.2825,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-09-05T13:55:00.000Z",
    endDatetime: "2025-09-05T14:25:00.000Z",
    coords: {
      lat: 45.6169,
      lon: 9.2825,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-09-06T12:15:00.000Z",
    endDatetime: "2025-09-06T13:00:00.000Z",
    coords: {
      lat: 45.6169,
      lon: 9.2825,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-09-07T07:45:00.000Z",
    endDatetime: "2025-09-07T08:45:00.000Z",
    coords: {
      lat: 45.6169,
      lon: 9.2825,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-09-19T06:00:00.000Z",
    endDatetime: "2025-09-19T06:45:00.000Z",
    coords: {
      lat: 40.3699,
      lon: 49.8433,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-09-19T10:00:00.000Z",
    endDatetime: "2025-09-19T10:30:00.000Z",
    coords: {
      lat: 40.3699,
      lon: 49.8433,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-09-20T10:15:00.000Z",
    endDatetime: "2025-09-20T11:00:00.000Z",
    coords: {
      lat: 40.3699,
      lon: 49.8433,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-09-21T07:00:00.000Z",
    endDatetime: "2025-09-21T08:00:00.000Z",
    coords: {
      lat: 40.3699,
      lon: 49.8433,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-11-28T11:05:00.000Z",
    endDatetime: "2025-11-28T11:50:00.000Z",
    coords: {
      lat: 25.490292,
      lon: 51.45303,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-11-28T16:10:00.000Z",
    endDatetime: "2025-11-28T16:40:00.000Z",
    coords: {
      lat: 25.490292,
      lon: 51.45303,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-11-29T16:20:00.000Z",
    endDatetime: "2025-11-29T17:05:00.000Z",
    coords: {
      lat: 25.490292,
      lon: 51.45303,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-11-30T12:00:00.000Z",
    endDatetime: "2025-11-30T13:00:00.000Z",
    coords: {
      lat: 25.490292,
      lon: 51.45303,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "free-practice",
    startDateTime: "2025-12-05T07:05:00.000Z",
    endDatetime: "2025-12-05T07:50:00.000Z",
    coords: {
      lat: 24.4821,
      lon: 54.3482,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "qualifying",
    startDateTime: "2025-12-05T11:00:00.000Z",
    endDatetime: "2025-12-05T11:30:00.000Z",
    coords: {
      lat: 24.4821,
      lon: 54.3482,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "sprint",
    startDateTime: "2025-12-06T12:15:00.000Z",
    endDatetime: "2025-12-06T13:00:00.000Z",
    coords: {
      lat: 24.4821,
      lon: 54.3482,
    },
  },
  {
    formulaSlug: "f2",
    sessionTypeSlug: "feature",
    startDateTime: "2025-12-07T09:15:00.000Z",
    endDatetime: "2025-12-07T10:15:00.000Z",
    coords: {
      lat: 24.4821,
      lon: 54.3482,
    },
  },
];
